<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Admin Login Page</title>
    <base href="<?=static::getUrl();?>"/>
    <link type="text/css" href="css/admin.css" rel="stylesheet"/>
</head>
<body class="<?=static::getPageClass();?>">
<main>
    <form method="post" action="<?=static::getUrl('admin/dashboard');?>">
        <p>Admin Login</p>
        <p><input type="email" name="username" placeholder="User Name"/></p>
        <p><input type="password" name="password" placeholder="........"/></p>
        <?php if(isset(static::$_errors['message']) && !empty(static::$_errors['message'])):?>
            <p class="error-message"><?=static::$_errors['message']?></p>
        <?php endif;?>
        <p><input type="submit" value="Login"/></p>
    </form>
</main>
</body>
</html>