<article>
    <header>
        <h1><?=static::getTitle()?></h1>
    </header>
    <footer>
        <p>Bonjour,c'est un page php en utilisant HTML/CSS (responsive) et Mysql avec l'architecture MVC, il s'agit
            du'un exercice de
            notre
            professeur Pierre Alexis.</p>
        <p>
            <h2>Table des matières au TD2</h2>
            <a href="https://www.solminihac.fr/sil-da2i/td-php-objet-mvc.html#3" target="_blank">Introduction et pré-requis</a>
        </p>
        <ul>
            <li>
                <a href="https://www.solminihac.fr/sil-da2i/td-php-objet-mvc.html#limites" target="_blank">
                    Étape 1 : limites de l'architecture</a>
            </li>
            <li>
                <a href="https://www.solminihac.fr/sil-da2i/td-php-objet-mvc.html#ameliorations" target="_blank">
                    Étape 2 : améliorations de l'architecture  </a>
            </li>
            <li>
                <a href="https://www.solminihac.fr/sil-da2i/td-php-objet-mvc.html#rewrite" target="_blank">
                    Étape 3 : réécriture d'URL   </a>
            </li>
            <li>
                <a href="https://www.solminihac.fr/sil-da2i/td-php-objet-mvc.html#pdo" target="_blank">
                    Étape 4 : changement de base</a>
            </li>
            <li>
                <a href="https://www.solminihac.fr/sil-da2i/td-php-objet-mvc.html#crud" target="_blank">
                    Étape 5 : site administrable</a>
            </li>
            <li>
                <a href="https://www.solminihac.fr/sil-da2i/td-php-objet-mvc.html#versionning" target="_blank">
                    Étape 6 : versionning</a>
            </li>
        </ul>
        <address>
            <h2>About Author</h2>
            <p><label>Nom et Prénom : </label><span>ZHANG Zhao</span></p>
            <p><label>Adresse e-mail : </label><a href="mailto:zo.zhang@gmail.com">zo.zhang@gmail.com</a></p>
        </address>
    </footer>
</article>