<section>
<?php if($_director = static::getDirector()):?>
        <article>
            <figure>
                <img src="<?=$_director->path;?>" alt="<?=$_director->legend;?>"/>
                <figcaption>
                    <p><span>Name: </span> <?=$_director->firstname;?> <?=$_director->lastname;?></p>
                    <p><span>Naissance: </span> <time datetime="<?=$_director->birthDate;?>"><?=$_director->format_birthDate;?> </time></p>
                </figcaption>
            </figure>
            <header>
                <h1>BIOGRAPHIE</h1>
                <p>
                    <?=$_director->biography;?>
                </p>
            </header>
        </article>
<?php endif;?>