<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Le Silence des agneaux</title>
    <base href="<?=static::getUrl();?>"/>
    <link type="text/css" href="css/main.css" rel="stylesheet"/>
</head>
<body class="<?=static::getPageClass();?>">
<nav>
    <ul>
        <li><a href="<?=static::getUrl('home');?>">Home</a></li>
        <li><a href="<?=static::getUrl('director');?>id/5/">Director</a></li>
        <li><a href="<?=static::getUrl('actor');?>id/1/">Casting</a></li>
        <li><a href="<?=static::getUrl('about');?>">About</a></li>
    </ul>
</nav>
<main>